### ISSUE TITLE
Descripcion para entidad video

### ISSUE THREAD

**Issue by MRico98** [DiegoAvmor/RestfulStreamingAPI#12]
Pienso que la entidad Video deberia contar con el atributo *descripcion*, tanto por la propia logica de la entidad como para complementar la accion de editar video que ahora unicamente permite editar el titulo

**Comment by DiegoAvmor** [comment]
@MRico98  acepto la mejora, incluyelo en el siguiente cambio que hagas respecto al crud de videos

**Comment by MRico98** [comment]
Resuelto en #17
