### ISSUE TITLE
Formacion incorrecta en URL de los api request

### ISSUE THREAD

**Issue by MRico98** [DiegoAvmor/RestfulStreamingAPI#9]
Cada URL para el proceso rest parece tener el mismo url base **(/api/....),** esto parece correcto pero tambien considero buena practica agregar informacion extra a cada enpoint, informacion relacionada con la entidad manejada **(/api/user/,/api/video)** etc.

**Comment by DiegoAvmor** [comment]
Para el caso de login/register esa bien dejarlo asi, para los video si hay que cambiarlo

**Comment by MRico98** [comment]
Dejamos todo el user controller asi entonces? @DiegoAvmor

**Comment by DiegoAvmor** [comment]
Solo para el login/register, cualquier otra cosa relacionado al usuario si hay que adecuarlo, de hecho la obtencion de la lista de recomendaciones del usuario esta en el endpoint users/{id}/recommendation que tiene el formato correcto. Los otros endpoints los deje de prueba para que vieran la parte de los roles

**Comment by MRico98** [comment]
Corregido en rama #11 . Esperando aceptacion de pull request
